name = "fishcards"
compatibility_date = "2026-02-15"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[site]
bucket = "./dist"
